### PR TITLE
✨ [feature] Add a dynamic gallery feature to car details modal

### PR DESCRIPTION
**Pull request by ladunjexa**
Hi Adrian!
The gallery in the modal that currently displays the details of the vehicle is static, meaning the images remain in place.

I have added a new feature using useState and useEffect that makes the gallery dynamic. Now, when you click on an image from the gallery (the three images below the main image), the main image will be replaced by the selected one, and so on.

I also want to express my sincere gratitude for all your work and contributions to the community. I have learned a lot from you 🙏

### CODE REVIEW

**Comment by yungxix** [comment]
Lovely! But am having issues running the file locally, it giving me an error stating TypeError: Class extends value undefined is not a constructor or null. I think the problem is from the node modules, I've had to delete the node modules on multiple occasions but still getting the same error.

**Comment by ladunjexa** [comment]
> Lovely! But am having issues running the file locally, it giving me an error stating TypeError: Class extends value undefined is not a constructor or null. I think the problem is from the node modules, I've had to delete the node modules on multiple occasions but still getting the same error.

Hi _yungxix_,
The error message you got typically occurs when you try to extend a class that is either undefined or null.
Regarding my commits, there is no reason for this error to pop up.

In my humble opinion, first delete `package-lock.json` file, the folder `node_modules`,  then execute `npm install` command to get the required packages. If the error persists try to install the used `@types/*` by execute the following command:
```bash
npm install --save @types/node @types/react  @types/react-dom
```
 and `Restart TS Server` via the editor command (`Ctrl+Shift+P`).
If nothing changes, maybe try to install `@types/*` as a devDependencies adding, `npm install --save-dev ...` - *I would point out that this is not recommended* (take a look at Dan Abramov's answer at [this](https://github.com/facebook/create-react-app/issues/6180) issue).

**Comment by yungxix** [comment]
I was still having the same issue! I ran the command to "npx create-next-app@latest ./"  to start the project, after executing all the necessary commands and dependencies were added it, and immediately I
error_node

 ran the npm run dev the issue came up again " [Symbol.iterator]() {
            ^

TypeError: Class extends value undefined is not a constructor or null "

**Comment by simrin3308** [comment]
seems interesting

**Comment by ladunjexa** [comment]
> I was still having the same issue! I ran the command to "npx create-next-app@latest ./" to start the project, after executing all the necessary commands and dependencies were added it, and immediately I error_node
> 
> ran the npm run dev the issue came up again " Symbol.iterator { ^
> 
> TypeError: Class extends value undefined is not a constructor or null "

I am not sure I got you well. Once you clone this repo and try to use it or run it you didnt have to run create-next-app, since you didnt actually create app (this command used to create new next.js app). The package.json file take care about dependencies that used in the project, so once you have the repo directory in your pc, run npm install to install the required dependencies and npm run dev to run the development server. Let me know if I got you uncorrectly.

**Pull request closed without merging**
